Traceback (most recent call last):
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\zulfa\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = pd.read_excel("/content/drive/MyDrive/kuliah sem 5/PSD/Mydata/ice_cream.xlsx")
df['DATE'] = pd.to_datetime(df['DATE'])

# Set DATE as index
df.set_index('DATE', inplace=True)
df
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_excel[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m/content/drive/MyDrive/kuliah sem 5/PSD/Mydata/ice_cream.xlsx[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      2[0m df[[38;5;124m'[39m[38;5;124mDATE[39m[38;5;124m'[39m] [38;5;241m=[39m pd[38;5;241m.[39mto_datetime(df[[38;5;124m'[39m[38;5;124mDATE[39m[38;5;124m'[39m])
[0;32m      4[0m [38;5;66;03m# Set DATE as index[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\excel\_base.py:495[0m, in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)[0m
[0;32m    493[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[0;32m    494[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m--> 495[0m     io [38;5;241m=[39m [43mExcelFile[49m[43m([49m
[0;32m    496[0m [43m        [49m[43mio[49m[43m,[49m
[0;32m    497[0m [43m        [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[0;32m    498[0m [43m        [49m[43mengine[49m[38;5;241;43m=[39;49m[43mengine[49m[43m,[49m
[0;32m    499[0m [43m        [49m[43mengine_kwargs[49m[38;5;241;43m=[39;49m[43mengine_kwargs[49m[43m,[49m
[0;32m    500[0m [43m    [49m[43m)[49m
[0;32m    501[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[0;32m    502[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    503[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[0;32m    504[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[0;32m    505[0m     )

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\excel\_base.py:1550[0m, in [0;36mExcelFile.__init__[1;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)[0m
[0;32m   1548[0m     ext [38;5;241m=[39m [38;5;124m"[39m[38;5;124mxls[39m[38;5;124m"[39m
[0;32m   1549[0m [38;5;28;01melse[39;00m:
[1;32m-> 1550[0m     ext [38;5;241m=[39m [43minspect_excel_format[49m[43m([49m
[0;32m   1551[0m [43m        [49m[43mcontent_or_path[49m[38;5;241;43m=[39;49m[43mpath_or_buffer[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m
[0;32m   1552[0m [43m    [49m[43m)[49m
[0;32m   1553[0m     [38;5;28;01mif[39;00m ext [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m   1554[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m   1555[0m             [38;5;124m"[39m[38;5;124mExcel file format cannot be determined, you must specify [39m[38;5;124m"[39m
[0;32m   1556[0m             [38;5;124m"[39m[38;5;124man engine manually.[39m[38;5;124m"[39m
[0;32m   1557[0m         )

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\excel\_base.py:1402[0m, in [0;36minspect_excel_format[1;34m(content_or_path, storage_options)[0m
[0;32m   1399[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(content_or_path, [38;5;28mbytes[39m):
[0;32m   1400[0m     content_or_path [38;5;241m=[39m BytesIO(content_or_path)
[1;32m-> 1402[0m [38;5;28;01mwith[39;00m [43mget_handle[49m[43m([49m
[0;32m   1403[0m [43m    [49m[43mcontent_or_path[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mis_text[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m
[0;32m   1404[0m [43m[49m[43m)[49m [38;5;28;01mas[39;00m handle:
[0;32m   1405[0m     stream [38;5;241m=[39m handle[38;5;241m.[39mhandle
[0;32m   1406[0m     stream[38;5;241m.[39mseek([38;5;241m0[39m)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\common.py:882[0m, in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    873[0m         handle [38;5;241m=[39m [38;5;28mopen[39m(
[0;32m    874[0m             handle,
[0;32m    875[0m             ioargs[38;5;241m.[39mmode,
[1;32m   (...)[0m
[0;32m    878[0m             newline[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m,
[0;32m    879[0m         )
[0;32m    880[0m     [38;5;28;01melse[39;00m:
[0;32m    881[0m         [38;5;66;03m# Binary mode[39;00m
[1;32m--> 882[0m         handle [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mhandle[49m[43m,[49m[43m [49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m)[49m
[0;32m    883[0m     handles[38;5;241m.[39mappend(handle)
[0;32m    885[0m [38;5;66;03m# Convert BytesIO or file objects passed with an encoding[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/content/drive/MyDrive/kuliah sem 5/PSD/Mydata/ice_cream.xlsx'

